Update single.yml

diff --git a/.github/workflows/single.yml b/.github/workflows/single.yml
--- a/.github/workflows/single.yml
+++ b/.github/workflows/single.yml
@@ -35,13 +35,22 @@ jobs:
 
       - name: Add_Dynv6_Domain
         run: |
+        
+          curl -sS --fail -w "%{http_code}" https://dynv6.com/api/v2/zones \
+                 -H "Authorization: Bearer ${dynv6_HTTP_Tokens}" \
+                 -H "Content-Type: application/json" \
+                 -H "Accept: application/json" || true  # 继续执行，即使curl失败
          
           for domain in $(cat 001) ; do \
-              curl -sS --fail -w "%{http_code}" https://dynv6.com/api/v2/zones \
-                  -H "Authorization: Bearer ${dynv6_HTTP_Tokens}" \
-                  -H "Content-Type: application/json" \
-                  -H "Accept: application/json" \
-                  --data '{"name": "'${domain}'"}' || true  # 继续执行，即使curl失败
+              # curl -sS --fail -w "%{http_code}" https://dynv6.com/api/v2/zones \
+              #     -H "Authorization: Bearer ${dynv6_HTTP_Tokens}" \
+              #     -H "Content-Type: application/json" \
+              #     -H "Accept: application/json" \
+              #     --data '{"name": "'${domain}'"}' || true  # 继续执行，即使curl失败
+
+
+
+              
           done
 
 
