Update single.yml

diff --git a/.github/workflows/single.yml b/.github/workflows/single.yml
--- a/.github/workflows/single.yml
+++ b/.github/workflows/single.yml
@@ -45,7 +45,21 @@ jobs:
           # 解析区域信息
           response="${response:0:-3}"
           zone_ids_info="$(jq -r '.[] | "\(.id) \(.name)"' <<< $response)"
-          echo "$zone_ids_info"
+
+          for domain in $(cat 001) ; do
+            echo "$zone_ids_info" | grep '$domain' | awk '{print $1}'
+            # curl -sS --fail -w "%{http_code}" https://dynv6.com/api/v2/zones/${zone_id}/records \
+            #    -H "Authorization: Bearer ${dynv6_HTTP_Tokens}" \
+            #    -H "Content-Type: application/json" \
+            #    -H "Accept: application/json" \
+            #    --data '{"type": "A", "name": "www", "data": "172.67.173.25"}' || true  # 继续执行，即使curl失败
+        
+            # curl -sS --fail -w "%{http_code}" https://dynv6.com/api/v2/zones/${zone_id}/records \
+            #    -H "Authorization: Bearer ${dynv6_HTTP_Tokens}" \
+            #    -H "Content-Type: application/json" \
+            #    -H "Accept: application/json" \
+            #    --data '{"type": "A", "name": "www", "data": "172.67.179.128"}' || true  # 继续执行，即使curl失败
+          done
          
           # for domain in $(cat 001) ; do \
               # curl -sS --fail -w "%{http_code}" https://dynv6.com/api/v2/zones \
